

players_injury:
  bodypart: knee
  data_path_in: './data/02_intermediate/player_injury_csvs/'
  data_path_out: './data/02_intermediate/'

data_prep:
  run_h5: False # set to True to generate tracking data h5 -- takes a while to run
